// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gxdwdjssteamfjmeigad.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imd4ZHdkanNzdGVhbWZqbWVpZ2FkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI3NzQyMzYsImV4cCI6MjA2ODM1MDIzNn0.XbSQHPx3Nw9KyW80RDoS-b5Qj5BSMFqMynVOM7CgCr0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});